import { PPQ, type Exercise } from '@/model'

export const AUDIO_DEMO_EXERCISE: Exercise = {
  id: 'audio-engine-test',
  title: 'Two-bar audio engine test',
  tempo: 80,
  timeSignature: { beats: 4, beatValue: 4 },
  bars: 2,
  events: [
    { voice: 'hihat', tick: 0, duration: PPQ },
    { voice: 'hihat', tick: 480, duration: PPQ / 2 },
    { voice: 'hihat', tick: 720, duration: PPQ / 2 },
    { voice: 'hihat', tick: 960, duration: PPQ / 4 },
    { voice: 'hihat', tick: 1_080, duration: PPQ / 4 },
    { voice: 'hihat', tick: 1_200, duration: PPQ / 4 },
    { voice: 'hihat', tick: 1_320, duration: PPQ / 4 },
    ...[1_440, 1_600, 1_760].map((tick) => ({
      voice: 'hihat' as const,
      tick,
      duration: PPQ / 3,
      tuplet: { num: 3, den: 2 },
    })),
    { voice: 'hihat', tick: 1_920, duration: PPQ / 2 },
    { voice: 'hihat', tick: 2_160, duration: PPQ / 2 },
    { voice: 'hihat', tick: 2_640, duration: PPQ / 2 },
    { voice: 'hihat', tick: 2_880, duration: PPQ },
    ...[3_360, 3_520, 3_680].map((tick) => ({
      voice: 'hihat' as const,
      tick,
      duration: PPQ / 3,
      tuplet: { num: 3, den: 2 },
    })),
    { voice: 'snare', tick: 480, duration: PPQ / 2 },
    {
      voice: 'snare',
      tick: 1_440,
      duration: PPQ / 3,
      tuplet: { num: 3, den: 2 },
    },
    { voice: 'snare', tick: 2_400, duration: PPQ / 2 },
    {
      voice: 'snare',
      tick: 3_360,
      duration: PPQ / 3,
      tuplet: { num: 3, den: 2 },
    },
    { voice: 'kick', tick: 0, duration: PPQ },
    { voice: 'kick', tick: 960, duration: PPQ },
    { voice: 'kick', tick: 1_920, duration: PPQ },
    { voice: 'kick', tick: 2_640, duration: PPQ / 2 },
    { voice: 'kick', tick: 2_880, duration: PPQ },
  ],
  tier: 'beginner',
  listenFirstAllowed: true,
  modes: ['playAlong', 'memorise'],
}
